- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # Пакеты из официальных репозиториев Arch/CachyOS
    pacman_packages:
      - nvidia-dkms
      - docker
      - telegram-desktop
      - discord
      - code
      - flameshot
      - gramps
      - libreoffice-fresh
      - qbittorrent
      - texmaker
      - thunderbird
      - firefox
      - virtualbox
      - virtualbox-host-dkms
      - vlc

    # Пакеты из AUR
    aur_packages:
      - jetbrains-toolbox
      - lazydocker
      - zed-editor
      - lmstudio-bin
      - obsidian
      - yandex-browser
      - warp-terminal
      - throne-bin
      - cursor-appimage-bin

  pre_tasks:
    - name: 🔑 Шаг 0. Принудительное обновление ключей CachyOS
      become: true
      pacman:
        name: cachyos-keyring
        state: latest

    - name: 🔑 Шаг 0.1. Обновление базы данных пакетов
      become: true
      pacman:
        update_cache: yes

  tasks:
    - name: 1. Обновление всех пакетов системы
      become: true
      pacman:
        upgrade: yes

    - name: 2. Установка 'base-devel' для сборки AUR пакетов
      become: true
      pacman:
        name: base-devel
        state: present

    - name: 3. Установка yay (AUR-хелпер)
      kewlfft.aur.aur:
        name: yay
        state: present
      become: false

    - name: 4. Установка пакетов из официальных репозиториев
      become: true
      pacman:
        name: "{{ pacman_packages }}"
        state: present

    - name: 5. Установка пакетов из AUR с помощью yay
      kewlfft.aur.aur:
        use: yay
        name: "{{ aur_packages }}"
        state: present
      become: false

    - name: 6. Настройка Docker
      become: true
      block:
        - name: Добавление пользователя в группу docker
          user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes

        - name: Включение и запуск Docker
          systemd:
            name: docker
            enabled: yes
            state: started

    - name: 7. Информационное сообщение
      debug:
        msg: |
          ========================================================================
          ✅ Установка завершена!
          
          ℹ️ ВАЖНО: Чтобы изменения для Docker, NVIDIA и VirtualBox вступили в силу,
          рекомендуется перезагрузить компьютер.

          Для VirtualBox может понадобиться:
          sudo modprobe vboxdrv
          ========================================================================
